[build]
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/app/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/.netlify/functions/send-notification"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"